### PR TITLE
Your commit message here

### PR DESCRIPTION
**Pull request by bitewulign**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
- I have created a directory, moved a directory, copied files to the directory, and so on.

## What did you learn from the changes you have made?
- For this assignment, I learned how to use Git for version control, create directories, move and copy files or directories, and perform other related tasks.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
- I believe we can directly edit the code in the Git repository instead of working on it locally.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
- Yes, there was a conflict, but the issue has been resolved.
## How were these changes tested?
-yes
## Checklist
- [ok ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by anjali-deshpande-hub** [comment]
Hello,
The autograder is not working because the branch has conflicts. Please resolve them. Thanks!

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Please resolve conflict and re-submit

**Review by monzchan — APPROVED** [review]
Great job! Please delete all the arrow '<' or '>' next time when you are trying to resolve the conflicts. Those arrows are how github indicate the conflicting part, so they should not appear after you have resolve the conflict.

**Review by monzchan — APPROVED** [review]
Good job! Your work is approved. But for next time, please make sure that you delete all the '<<<' and '>>>' and any unnecessary content at your file when you try to resolve conflicts.

**Pull request closed without merging**
